import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import NextTopLoader from 'nextjs-toploader';
import StartingPage from "@/hooks/StartingPage";

const inter = Inter({ subsets: ["latin"],weight:["400",'500','600','700','800','900'] });

export const metadata = {
  title: "Food App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} p-3 md:px-10 w-full bg-slate-100 min-h-screen `}>
        <StartingPage>
          <Toaster position="top-center" />
          <NextTopLoader color="#2299DD"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          
          shadow="0 0 10px #2299DD,0 0 5px #2299DD"/>
          <Navbar />
            {children}
          <Footer />
        </StartingPage>
        </body>
    </html>
  );
}
